seed: 0
output_dir: './reward_output'
load_checkpoint: '/work/mount/publicModel/TeleChat-12B/telechat_12b_base/telechat_12b_base.ckpt'
src_strategy_path_or_dir: ''
auto_trans_ckpt: False
only_save_strategy: False
resume_training: False
run_mode: 'reward_training'

# trainer config
trainer:
  type: RewardModelTrainer
  model_name: 'telechat_12b'

# runner config
runner_config:
  epochs: 10
  batch_size: 1
  sink_mode: True
  sink_size: 2
  gradient_accumulation_steps: 4

# optimizer
optimizer:
  type: FP32StateAdamWeightDecay
  beta1: 0.9
  beta2: 0.95
  eps: 1.e-8  
  learning_rate: 1.e-5

# lr schedule
lr_schedule:
  type: CosineWithWarmUpLR
  learning_rate: 1.e-5
  lr_end: 0
  warmup_ratio: 0.03
  total_steps: -1

# dataset
train_dataset: &train_dataset
  data_loader:
    type: GeneratorDataset
    dataset_dir: "/work/home/trian_ppo-main/train_ppo/data/0000 (1).json"
    shuffle: True
  input_columns: ["input_ids_chosen", "attention_mask_chosen", 
                 "input_ids_rejected", "attention_mask_rejected"]
  num_parallel_workers: 1
  python_multiprocessing: False
  drop_remainder: True
  batch_size: 1
  repeat: 1
  numa_enable: False
  prefetch_size: 1

train_dataset_task:
  type: RewardModelDataset
  dataset_config: *train_dataset

# 关闭评估
do_eval: False

# parallel context config
use_parallel: True
parallel:
  parallel_mode: 1
  gradients_mean: False
  enable_alltoall: False
  full_batch: True
  search_mode: "sharding_propagation"
  enable_parallel_optimizer: True
  strategy_ckpt_save_file: "./reward_strategy.ckpt"
  parallel_optimizer_config:
    gradient_accumulation_shard: False
    parallel_optimizer_threshold: 64

parallel_config:
  data_parallel: 8
  model_parallel: 1
  pipeline_stage: 1
  use_seq_parallel: False
  micro_batch_num: 32
  vocab_emb_dp: True
  gradient_aggregation_group: 8

micro_batch_interleave_num: 1

# recompute config
recompute_config:
  recompute: True
  select_recompute: False
  parallel_optimizer_comm_recompute: False
  mp_comm_recompute: True
  recompute_slice_activation: True

# callbacks
callbacks:
  - type: MFLossMonitor
  - type: CheckpointMointor
    prefix: "telechat_12b_reward"
    save_checkpoint_steps: 100
    integrated_save: False
    async_save: False
  - type: ObsMonitor

# mindspore context
context:
  mode: 0
  runtime_num_threads: 1
  device_target: "Ascend"
  enable_graph_kernel: False
  graph_kernel_flags: "--disable_expand_ops=Softmax,Dropout --enable_parallel_fusion=true --reduce_fuse_depth=8 --enable_auto_tensor_inplace=true"
  max_call_depth: 10000
  max_device_memory: "58GB"
  save_graphs: False
  save_graphs_path: "./reward_graph"
  # device_id: 0

# model config
model:
  model_config:
    type: TelechatConfig
    model_name: 'telechat_12b'
    batch_size: 1
    seq_length: 1024
    hidden_size: 5120
    num_layers: 38
    num_heads: 32
    vocab_size: 120000
    num_labels: 1  # 奖励模型特有
    rms_norm_eps: 1.0e-5
    bos_token_id: 1
    eos_token_id: 2
    pad_token_id: 3
    ignore_token_id: -100
    hidden_dropout_prob: 0.1
    attention_dropout_prob: 0.1
    ffn_dim_multiplier: 12288
    compute_dtype: "float32"
    layernorm_compute_type: "float32"
    softmax_compute_type: "float32"
    rotary_dtype: "float32"
    param_init_type: "float32"
    use_past: False
    pretrain_seqlen: 4096
    extend_method: "None"
    use_flash_attention: False
    offset: 0
    use_past_shard: False
    repetition_penalty: 1
    max_decode_length: 512
    top_k: 3
    top_p: 1
    do_sample: False
  arch:
    type: TelechatForSequenceClassification

processor:
  return_tensors: ms
  tokenizer:
    unk_token: '<unk>'
    bos_token: '<_start>'
    eos_token: '<_end>'
    pad_token: '<_pad>'
    type: TelechatTokenizer
  type: TelechatProcessor

metric:
  type: PerplexityMetric

runner_wrapper:
  type: MFTrainOneStepCell
  scale_sense:
    type: DynamicLossScaleUpdateCell
    loss_scale_value: 4096
    scale_factor: 2
    scale_window: 500
  use_clip_grad: True

eval_callbacks:
  - type: ObsMonitor

auto_tune: False
filepath_prefix: './reward_autotune'
autotune_per_step: 10

profile: False
profile_start_step: 1
profile_stop_step: 10
init_start_profile: False
profile_communication: False
profile_memory: True
layer_scale: False
layer_decay: 0.65
lr_scale_factor: 256