seed: 0
output_dir: './output'
load_checkpoint: '/work/mount/publicModel/TeleChat-12B/telechat_12b_base/telechat_12b_base.ckpt'
src_strategy_path_or_dir: ''
auto_trans_ckpt: False
only_save_strategy: False
resume_training: False
run_mode: 'inference'  # ref_model只用于推理

# trainer config
trainer:
  type: CausalLanguageModelingTrainer
  model_name: 'telechat_12b'

# runner config
runner_config:
  epochs: 1  # ref_model不需要训练
  batch_size: 2
  sink_mode: True
  sink_size: 2
  gradient_accumulation_steps: 1

# optimizer (实际不会使用，因为ref_model不训练)
optimizer:
  type: FP32StateAdamWeightDecay
  beta1: 0.9
  beta2: 0.999
  eps: 1.e-8
  learning_rate: 5.e-6

# lr schedule (实际不会使用)
lr_schedule:
  type: CosineWithWarmUpLR
  learning_rate: 5.e-6
  lr_end: 1.e-6
  warmup_ratio: 0.03
  total_steps: -1

# dataset
train_dataset: &train_dataset
  data_loader:
    type: MindDataset
    dataset_dir: "data/output_dataset.mindrecord"
    shuffle: False  # ref_model不需要shuffle
  input_columns: ["input_ids", "labels"]
  num_parallel_workers: 8
  python_multiprocessing: False
  drop_remainder: True
  batch_size: 2
  repeat: 1
  numa_enable: False
  prefetch_size: 1
train_dataset_task:
  type: CausalLanguageModelDataset
  dataset_config: *train_dataset

do_eval: False

use_parallel: True
parallel:
  parallel_mode: 1
  gradients_mean: False
  enable_alltoall: True
  full_batch: True
  search_mode: "sharding_propagation"
  enable_parallel_optimizer: True
  strategy_ckpt_save_file: "./ref_model_ckpt_strategy.ckpt"
  parallel_optimizer_config:
    gradient_accumulation_shard: False
    parallel_optimizer_threshold: 64

parallel_config:
  data_parallel: 4
  model_parallel: 2
  pipeline_stage: 1
  use_seq_parallel: False
  micro_batch_num: 64
  vocab_emb_dp: True
  gradient_aggregation_group: 4

micro_batch_interleave_num: 1

recompute_config:
  recompute: False  # ref_model不需要重计算
  select_recompute: False
  parallel_optimizer_comm_recompute: False
  mp_comm_recompute: True
  recompute_slice_activation: True

callbacks:
  - type: MFLossMonitor
  - type: ObsMonitor

context:
  mode: 0
  device_target: "Ascend"
  enable_graph_kernel: False
  graph_kernel_flags: "--disable_expand_ops=Softmax,Dropout --enable_parallel_fusion=true --reduce_fuse_depth=8 --enable_auto_tensor_inplace=true"
  max_call_depth: 10000
  max_device_memory: "58GB"
  save_graphs: False
  save_graphs_path: "./graph"
  device_id: 0

model:
  model_config:
    type: TelechatConfig
    model_name: 'telechat_12b'
    batch_size: 2
    seq_length: 1024
    hidden_size: 5120
    num_layers: 38
    num_heads: 32
    vocab_size: 120000
    rms_norm_eps: 1.0e-5
    bos_token_id: 1
    eos_token_id: 2
    pad_token_id: 3
    ignore_token_id: -100
    hidden_dropout_prob: 0.0  # 推理时关闭dropout
    attention_dropout_prob: 0.0  # 推理时关闭dropout
    ffn_dim_multiplier: 12288
    compute_dtype: "float16"
    layernorm_compute_type: "float32"
    softmax_compute_type: "float16"
    rotary_dtype: "float16"
    param_init_type: "float16"
    use_past: False
    pretrain_seqlen: 4096
    extend_method: "None"
    use_flash_attention: False
    offset: 0
    use_past_shard: False
    checkpoint_name_or_path: "telechat_12b"
    repetition_penalty: 1
    max_decode_length: 512
    top_k: 0
    top_p: 1
    do_sample: True
    temperature: 1.0
    is_ref_model: True  # 标记为参考模型
  arch:
    type: TelechatForCausalLM

processor:
  return_tensors: ms
  tokenizer:
    unk_token: '<unk>'
    bos_token: '<_start>'
    eos_token: '<_end>'
    pad_token: '<_pad>'
    type: TelechatTokenizer
  type: TelechatProcessor

metric:
  type: PerplexityMetric

runner_wrapper:
  type: MFTrainOneStepCell
  scale_sense:
    type: DynamicLossScaleUpdateCell
    loss_scale_value: 4096
    scale_factor: 2
    scale_window: 500
  use_clip_grad: True

eval_callbacks:
  - type: ObsMonitor

auto_tune: False
filepath_prefix: './autotune'
autotune_per_step: 10

profile: False
profile_start_step: 1
profile_stop_step: 10
init_start_profile: False
profile_communication: False
profile_memory: True
layer_scale: False
layer_decay: 0.65
lr_scale_factor: 256

remote_save_url: "Please input obs url on AICC platform."